version: '3.2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0.0
    volumes:
      - .:/src
      - .:/src
      - ~/.nuget/packages:/root/.nuget/packages
      - ~/.local/share/NuGet/v3-cache:/root/.local/share/NuGet/v3-cache
    working_dir: /src
    command: bash -c -e '${cmd}'
